FROM mhart/alpine-node:10

WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)

COPY ./web/package*.json ./app/
RUN cd ./app && npm install && ls -l
RUN npm i -g pm2

COPY ./web/. ./app/

# If you are building your code for production
# RUN npm ci --only=production

RUN cd ./app && npm run build

EXPOSE 8081

CMD [ "pm2-runtime", "start", "./app/ecosystem.config.js", "--only=app" ]
