version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: cache
    expose:
      - "${REDIS_PORT}"
    ports:
      - "6300:${REDIS_PORT}"
  web:
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
      - PORT=$PORT
      - CACHE_EXPIRY_TIME=$CACHE_EXPIRY_TIME
      - MAX_CAPACITY=$MAX_CAPACITY
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "${PORT}:8081"