version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: cache
    expose:
      - 6379
  web:
    links:
      - redis
    environment:
      - REDIS_URL=redis://cache
    build:
      context: .
      dockerfile: ./Dockerfile.web
    ports:
      - "8081:8081"